"""Constants shared by Model Context Protocol integrations."""

from __future__ import annotations

MCP_NO_COLOR_ENV = "NO_COLOR"
MCP_TERMINAL_ENV = "TERM"
MCP_TERMINAL_DUMB_VALUE = "dumb"
MCP_TOOL_LIST_MAX_PAGES = 100
MCP_TOOL_LIST_MAX_RESPONSE_BYTES = 4_500_000
MCP_TOOL_LIST_MAX_SERIALIZED_CHARS = 4_000_000
MCP_TOOL_LIST_MAX_TOOLS = 4_096
