"""Constants for the generic MCP gateway integration."""

from __future__ import annotations

MCP_GATEWAY_ALLOWED_TOOLS_ENV = "MCP_GATEWAY_ALLOWED_TOOLS"
MCP_GATEWAY_AUTH_TOKEN_ENV = "MCP_GATEWAY_AUTH_TOKEN"
MCP_GATEWAY_DEFAULT_TIMEOUT_SECONDS = 30.0
MCP_GATEWAY_TOOL_RESPONSE_MAX_BYTES = 1_000_000
MCP_GATEWAY_READ_ONLY_TOOLS_ENV = "MCP_GATEWAY_READ_ONLY_TOOLS"
MCP_GATEWAY_URL_ENV = "MCP_GATEWAY_URL"
