"""Shared budgets for tool observations, capture, and persistence."""

DEFAULT_TOOL_OUTPUT_TOKENS = 10_000
TOOL_OUTPUT_BYTES_PER_TOKEN = 4
TOOL_OUTPUT_HISTORY_NUMERATOR = 6
TOOL_OUTPUT_HISTORY_DENOMINATOR = 5
TOOL_OUTPUT_CAPTURE_MAX_BYTES = 1024 * 1024
TOOL_OUTPUT_PERSIST_MAX_BYTES = 64 * 1024
OPENSRE_TOOL_OUTPUT_TOKEN_LIMIT_ENV = "OPENSRE_TOOL_OUTPUT_TOKEN_LIMIT"

__all__ = [
    "DEFAULT_TOOL_OUTPUT_TOKENS",
    "OPENSRE_TOOL_OUTPUT_TOKEN_LIMIT_ENV",
    "TOOL_OUTPUT_BYTES_PER_TOKEN",
    "TOOL_OUTPUT_CAPTURE_MAX_BYTES",
    "TOOL_OUTPUT_HISTORY_DENOMINATOR",
    "TOOL_OUTPUT_HISTORY_NUMERATOR",
    "TOOL_OUTPUT_PERSIST_MAX_BYTES",
]
