"""Shared limits and credential names for source-bound auto-triage."""

TRIAGE_PENDING_LIMIT = 1000
TRIAGE_SECONDS = 180
TRIAGE_TOOL_CALLS = 12
TRIAGE_MODEL_ITERATIONS = 8
TRIAGE_WINDOW_SECONDS = 3600
TRIAGE_LEASE_SECONDS = 20
TRIAGE_POLL_SECONDS = 0.5
TRIAGE_TEXT_LIMIT = 16000
TRIAGE_CREDENTIAL_PREFIX = "OPENSRE_TRIAGE_"
