"""Generated views over the memory directory: ``MEMORY.md`` and the two prompt blocks.

The prompt sees memory twice:

- the **index** — every memory as one ``[type] name — description`` line, most
  useful first, plus ``memory_summary.md`` above it. It changes only when the
  memories change, so it sits in the cached half of the prompt;
- **relevant memories** — full bodies of the few memories that match the
  current request, rebuilt every turn.
"""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from pathlib import Path

from core.domain.memory.files import INDEX_FILENAME, write_text_atomically
from core.domain.memory.models import TRUNCATION_MARKER, MemoryRecord, MemoryType
from core.domain.memory.usage import MemoryUsage

_INDEX_HEADER = (
    "# Long-term memory index\n"
    "\n"
    "<!-- Generated by OpenSRE after every memory write; safe to delete "
    "(rebuilt on next write). Edit the individual .md files instead. -->\n"
    "\n"
)

DEFAULT_PROMPT_INDEX_CHARS = 2_000
"""Budget for the index lines in the cached prompt (the summary is budgeted separately)."""
INDEX_DESCRIPTION_CHARS = 120
DEFAULT_RELEVANT_MEMORY_ITEMS = 5
DEFAULT_RELEVANT_MEMORY_CHARS = 4_000
RELEVANT_BODY_CHARS = 1_200
#: A memory is shortened to fit the remaining budget only when at least this much is left.
_MIN_PARTIAL_ENTRY_CHARS = 400
_ELLIPSIS = "…"


def _memory_md_line(record: MemoryRecord) -> str:
    updated_day = record.updated_at[:10]
    return f"- [{record.memory_type}] {record.slug} — {record.description} (updated {updated_day})"


def write_index(directory: Path, records: list[MemoryRecord]) -> Path:
    """Rewrite MEMORY.md from supplied records. May raise ``OSError``."""
    lines = [_memory_md_line(record) for record in records]
    body = "\n".join(lines) + "\n" if lines else "(no memories stored yet)\n"
    path = directory / INDEX_FILENAME
    write_text_atomically(path, _INDEX_HEADER + body)
    return path


def _type_rank(memory_type: MemoryType) -> int:
    if memory_type is MemoryType.USER:
        return 0
    if memory_type is MemoryType.PREFERENCE:
        return 1
    return 2


def index_order(
    records: Sequence[MemoryRecord], usage: Mapping[str, MemoryUsage]
) -> list[MemoryRecord]:
    """Most useful first: ``user``, then ``preference``, then the rest.

    Within a group, the memory touched most recently — updated or put in front
    of the model — comes first, then the more often used, then by name.
    """
    unused = MemoryUsage()

    def last_activity(record: MemoryRecord) -> str:
        return max(record.updated_at, usage.get(record.slug, unused).last_used_at)

    # Stable sorts, least significant key first.
    ordered = sorted(records, key=lambda record: record.slug)
    ordered.sort(key=lambda record: usage.get(record.slug, unused).use_count, reverse=True)
    ordered.sort(key=last_activity, reverse=True)
    ordered.sort(key=lambda record: _type_rank(record.memory_type))
    return ordered


def _clip(text: str, limit: int) -> str:
    text = " ".join(text.split())
    return text if len(text) <= limit else text[: limit - 1].rstrip() + _ELLIPSIS


def _index_line(record: MemoryRecord) -> str:
    description = _clip(record.description, INDEX_DESCRIPTION_CHARS)
    return f"- [{record.memory_type}] {record.slug} — {description}"


def render_index_lines(records: Sequence[MemoryRecord], *, max_chars: int) -> str:
    """One line per memory in the given order, cut at ``max_chars`` with a recall pointer."""
    lines: list[str] = []
    used = 0
    for record in records:
        line = _index_line(record)
        cost = len(line) + (1 if lines else 0)
        if used + cost > max_chars:
            break
        lines.append(line)
        used += cost
    hidden = len(records) - len(lines)
    if hidden > 0:
        lines.append(f"… and {hidden} more (memory_recall)")
    return "\n".join(lines)


def render_prompt_index(
    records: Sequence[MemoryRecord],
    *,
    usage: Mapping[str, MemoryUsage],
    summary: str = "",
    max_chars: int = DEFAULT_PROMPT_INDEX_CHARS,
) -> str:
    """The cached memory block: the consolidated summary, then the index lines.

    ``""`` when there is neither a summary nor a memory to list.
    """
    lines = render_index_lines(index_order(records, usage), max_chars=max(max_chars, 0))
    summary = summary.strip()
    if not summary:
        return lines
    parts = [
        "Summary (consolidated from these memories and recent sessions; a memory "
        "below wins where they differ):",
        summary,
    ]
    if lines:
        parts.extend(("", "Index:", lines))
    return "\n".join(parts)


def _provenance_note(record: MemoryRecord) -> str:
    if record.source is None:
        return ""
    note = f"; from {record.source}"
    if record.verified:
        note += ", verified"
    if record.evidence:
        note += f": {_clip(record.evidence, 120)}"
    return note


def _relevant_entry(record: MemoryRecord, *, body_chars: int) -> str:
    header = (
        f"[{record.memory_type}] {record.slug} — {_clip(record.description, 200)} "
        f"(updated {record.updated_at[:10]}{_provenance_note(record)})"
    )
    body = record.body.strip()
    if len(body) > body_chars:
        body = body[: max(body_chars - len(TRUNCATION_MARKER), 0)].rstrip() + TRUNCATION_MARKER
    return f"{header}\n{body}" if body else header


def render_relevant_entries(
    ranked: Sequence[MemoryRecord],
    *,
    max_items: int = DEFAULT_RELEVANT_MEMORY_ITEMS,
    max_chars: int = DEFAULT_RELEVANT_MEMORY_CHARS,
) -> tuple[str, list[str]]:
    """Full entries for ``ranked`` (already in priority order) within the budgets.

    Returns the text and the slugs it includes. An entry that does not fit is
    shortened when enough budget remains, otherwise skipped for a smaller one.
    """
    entries: list[str] = []
    slugs: list[str] = []
    remaining = max(max_chars, 0)
    for record in ranked:
        if len(entries) >= max_items:
            break
        separator = 2 if entries else 0
        entry = _relevant_entry(record, body_chars=RELEVANT_BODY_CHARS)
        if len(entry) + separator > remaining:
            room = remaining - separator
            if room < _MIN_PARTIAL_ENTRY_CHARS:
                continue
            shown_body = min(len(record.body.strip()), RELEVANT_BODY_CHARS)
            entry = _relevant_entry(record, body_chars=shown_body - (len(entry) - room))
            if len(entry) > room:
                continue
        entries.append(entry)
        slugs.append(record.slug)
        remaining -= len(entry) + separator
    return "\n\n".join(entries), slugs


__all__ = [
    "DEFAULT_PROMPT_INDEX_CHARS",
    "DEFAULT_RELEVANT_MEMORY_CHARS",
    "DEFAULT_RELEVANT_MEMORY_ITEMS",
    "INDEX_DESCRIPTION_CHARS",
    "RELEVANT_BODY_CHARS",
    "index_order",
    "render_index_lines",
    "render_prompt_index",
    "render_relevant_entries",
    "write_index",
]
